<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HyperMemory.Core\HyperMemory.Core.csproj" />
    <ProjectReference Include="..\HyperMemory.Infrastructure\HyperMemory.Infrastructure.csproj" />
  </ItemGroup>

</Project>
